FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.0

# 安装 IK 分词器插件（--batch 参数自动确认）
RUN elasticsearch-plugin install --batch https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-8.11.0.zip
