"""initial migration

Revision ID: 865837abd4b7
Revises: 
Create Date: 2025-11-13 22:00:32.639867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '865837abd4b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_config',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False, comment='模型类型：llm/embedding/rerank 等'),
    sa.Column('scenario', sa.String(length=50), nullable=False, comment='使用场景：general/extract/search/chat/summary 等（当前LLM已细分，embedding等使用general）'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='供应商标识（如：openai, anthropic, 302ai, custom）'),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False, comment='温度(0.00-2.00)'),
    sa.Column('max_tokens', sa.Integer(), nullable=False, comment='最大输出token数'),
    sa.Column('top_p', sa.Numeric(precision=3, scale=2), nullable=False, comment='top_p(0.00-1.00)'),
    sa.Column('frequency_penalty', sa.Numeric(precision=3, scale=2), nullable=False, comment='频率惩罚(-2.00-2.00)'),
    sa.Column('presence_penalty', sa.Numeric(precision=3, scale=2), nullable=False, comment='存在惩罚(-2.00-2.00)'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='超时时间(秒)'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='最大重试次数'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='扩展数据（如embedding的dimensions, rerank的top_n等）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级（同场景内，数字越大越优先）'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.CHAR(length=36), nullable=True, comment='创建人ID（预留）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_config'))
    )
    op.create_index('idx_scenario', 'model_config', ['scenario'], unique=False)
    op.create_index('idx_type', 'model_config', ['type'], unique=False)
    op.create_index('idx_type_scenario_active_priority', 'model_config', ['type', 'scenario', 'is_active', 'priority'], unique=False)
    op.create_index(op.f('ix_model_config_is_active'), 'model_config', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_config_scenario'), 'model_config', ['scenario'], unique=False)
    op.create_index(op.f('ix_model_config_type'), 'model_config', ['type'], unique=False)
    op.create_table('source_config',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_config'))
    )
    op.create_table('article',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_config_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_config_id'], ['source_config.id'], name=op.f('fk_article_source_config_id_source_config'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    op.create_index('idx_category', 'article', ['category'], unique=False)
    op.create_index('idx_source_config_id', 'article', ['source_config_id'], unique=False)
    op.create_index('idx_source_config_status', 'article', ['source_config_id', 'status'], unique=False)
    op.create_index(op.f('ix_article_category'), 'article', ['category'], unique=False)
    op.create_index(op.f('ix_article_source_config_id'), 'article', ['source_config_id'], unique=False)
    op.create_table('chat_conversation',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_config_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_message_time', sa.DateTime(), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('del_flag', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0：正常；1：已删除）'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['source_config_id'], ['source_config.id'], name=op.f('fk_chat_conversation_source_config_id_source_config'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_conversation'))
    )
    op.create_index('idx_source_last_msg', 'chat_conversation', ['source_config_id', 'last_message_time'], unique=False)
    op.create_index(op.f('ix_chat_conversation_source_config_id'), 'chat_conversation', ['source_config_id'], unique=False)
    op.create_table('article_section',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('article_id', sa.CHAR(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_article_section_article_id_article'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_section'))
    )
    op.create_index('idx_article_id', 'article_section', ['article_id'], unique=False)
    op.create_index('idx_article_rank', 'article_section', ['article_id', 'rank'], unique=False)
    op.create_index(op.f('ix_article_section_article_id'), 'article_section', ['article_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('conversation_id', sa.CHAR(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('sender_avatar', sa.String(length=255), nullable=True),
    sa.Column('sender_title', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sender_role', sa.String(length=50), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('del_flag', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0：正常；1：已删除）'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], name=op.f('fk_chat_message_conversation_id_chat_conversation'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_index('idx_conv_timestamp', 'chat_message', ['conversation_id', 'timestamp'], unique=False)
    op.create_index('idx_del_flag', 'chat_message', ['del_flag'], unique=False)
    op.create_index('idx_sender_id', 'chat_message', ['sender_id'], unique=False)
    op.create_index('idx_type', 'chat_message', ['type'], unique=False)
    op.create_index(op.f('ix_chat_message_conversation_id'), 'chat_message', ['conversation_id'], unique=False)
    op.create_table('entity_type',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='global', nullable=False, comment='应用范围：global/source/article'),
    sa.Column('source_config_id', sa.CHAR(length=36), nullable=True),
    sa.Column('article_id', sa.CHAR(length=36), nullable=True, comment='文档ID（仅 scope=article 时有值）'),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('similarity_threshold', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('value_format', sa.String(length=100), nullable=True),
    sa.Column('value_constraints', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_entity_type_article_id_article'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_config_id'], ['source_config.id'], name=op.f('fk_entity_type_source_config_id_source_config'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_type'))
    )
    op.create_index('idx_default_active', 'entity_type', ['is_default', 'is_active'], unique=False)
    op.create_index(op.f('ix_entity_type_article_id'), 'entity_type', ['article_id'], unique=False)
    op.create_index(op.f('ix_entity_type_scope'), 'entity_type', ['scope'], unique=False)
    op.create_index(op.f('ix_entity_type_source_config_id'), 'entity_type', ['source_config_id'], unique=False)
    op.create_index('uk_scope_source_config_article_type', 'entity_type', ['scope', 'source_config_id', 'article_id', 'type'], unique=True)
    op.create_table('source_chunk',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_config_id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('article_id', sa.CHAR(length=36), nullable=True),
    sa.Column('conversation_id', sa.CHAR(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('chunk_length', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_source_chunk_article_id_article'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], name=op.f('fk_source_chunk_conversation_id_chat_conversation'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_config_id'], ['source_config.id'], name=op.f('fk_source_chunk_source_config_id_source_config'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_chunk')),
    comment='来源片段聚合表 - 聚合ArticleSection或ChatMessage为片段'
    )
    op.create_index('idx_article_id', 'source_chunk', ['article_id'], unique=False)
    op.create_index('idx_conversation_id', 'source_chunk', ['conversation_id'], unique=False)
    op.create_index('idx_created', 'source_chunk', ['created_time'], unique=False)
    op.create_index('idx_source', 'source_chunk', ['source_type', 'source_id', 'rank'], unique=False)
    op.create_index('idx_source_config_id', 'source_chunk', ['source_config_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_article_id'), 'source_chunk', ['article_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_conversation_id'), 'source_chunk', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_source_config_id'), 'source_chunk', ['source_config_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_source_id'), 'source_chunk', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_source_type'), 'source_chunk', ['source_type'], unique=False)
    op.create_table('source_event',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_config_id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源类型：ARTICLE/CHAT'),
    sa.Column('source_id', sa.String(length=100), nullable=False, comment='来源ID'),
    sa.Column('article_id', sa.CHAR(length=36), nullable=True),
    sa.Column('conversation_id', sa.CHAR(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False, comment='层级深度（0=顶层）'),
    sa.Column('parent_id', sa.CHAR(length=36), nullable=True, comment='父事项ID（自引用）'),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('chunk_id', sa.CHAR(length=36), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_source_event_article_id_article'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], name=op.f('fk_source_event_conversation_id_chat_conversation'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['source_event.id'], name=op.f('fk_source_event_parent_id_source_event'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_config_id'], ['source_config.id'], name=op.f('fk_source_event_source_config_id_source_config'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_event'))
    )
    op.create_index('idx_article_id', 'source_event', ['article_id'], unique=False)
    op.create_index('idx_article_rank', 'source_event', ['article_id', 'rank'], unique=False)
    op.create_index('idx_chunk_id', 'source_event', ['chunk_id'], unique=False)
    op.create_index('idx_conversation_id', 'source_event', ['conversation_id'], unique=False)
    op.create_index('idx_end_time', 'source_event', ['end_time'], unique=False)
    op.create_index('idx_level', 'source_event', ['level'], unique=False)
    op.create_index('idx_parent_id', 'source_event', ['parent_id'], unique=False)
    op.create_index('idx_parent_level', 'source_event', ['parent_id', 'level'], unique=False)
    op.create_index('idx_source', 'source_event', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_source_config_id', 'source_event', ['source_config_id'], unique=False)
    op.create_index('idx_source_rank', 'source_event', ['source_type', 'source_id', 'rank'], unique=False)
    op.create_index('idx_start_time', 'source_event', ['start_time'], unique=False)
    op.create_index(op.f('ix_source_event_article_id'), 'source_event', ['article_id'], unique=False)
    op.create_index(op.f('ix_source_event_chunk_id'), 'source_event', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_source_event_conversation_id'), 'source_event', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_source_event_parent_id'), 'source_event', ['parent_id'], unique=False)
    op.create_index(op.f('ix_source_event_source_config_id'), 'source_event', ['source_config_id'], unique=False)
    op.create_index(op.f('ix_source_event_source_id'), 'source_event', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_event_source_type'), 'source_event', ['source_type'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_config_id', sa.CHAR(length=36), nullable=True),
    sa.Column('article_id', sa.CHAR(length=36), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_task_article_id_article'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_config_id'], ['source_config.id'], name=op.f('fk_task_source_config_id_source_config'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_index('idx_article_id', 'task', ['article_id'], unique=False)
    op.create_index('idx_created_time', 'task', ['created_time'], unique=False)
    op.create_index('idx_source_config_id', 'task', ['source_config_id'], unique=False)
    op.create_index('idx_status', 'task', ['status'], unique=False)
    op.create_index('idx_status_created', 'task', ['status', 'created_time'], unique=False)
    op.create_index('idx_task_type', 'task', ['task_type'], unique=False)
    op.create_index(op.f('ix_task_article_id'), 'task', ['article_id'], unique=False)
    op.create_index(op.f('ix_task_source_config_id'), 'task', ['source_config_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_task_type'), 'task', ['task_type'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_config_id', sa.CHAR(length=36), nullable=False),
    sa.Column('entity_type_id', sa.CHAR(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('value_raw', sa.Text(), nullable=True),
    sa.Column('int_value', sa.BigInteger(), nullable=True),
    sa.Column('float_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('datetime_value', sa.DateTime(), nullable=True),
    sa.Column('bool_value', sa.Boolean(), nullable=True),
    sa.Column('enum_value', sa.String(length=100), nullable=True),
    sa.Column('value_unit', sa.String(length=50), nullable=True),
    sa.Column('value_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_type.id'], name=op.f('fk_entity_entity_type_id_entity_type'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_config_id'], ['source_config.id'], name=op.f('fk_entity_source_config_id_source_config'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity'))
    )
    op.create_index('idx_entity_type_id', 'entity', ['entity_type_id'], unique=False)
    op.create_index('idx_normalized_name', 'entity', ['normalized_name'], unique=False)
    op.create_index('idx_source_config_id', 'entity', ['source_config_id'], unique=False)
    op.create_index('idx_source_config_type', 'entity', ['source_config_id', 'type'], unique=False)
    op.create_index(op.f('ix_entity_datetime_value'), 'entity', ['datetime_value'], unique=False)
    op.create_index(op.f('ix_entity_entity_type_id'), 'entity', ['entity_type_id'], unique=False)
    op.create_index(op.f('ix_entity_enum_value'), 'entity', ['enum_value'], unique=False)
    op.create_index(op.f('ix_entity_float_value'), 'entity', ['float_value'], unique=False)
    op.create_index(op.f('ix_entity_int_value'), 'entity', ['int_value'], unique=False)
    op.create_index(op.f('ix_entity_normalized_name'), 'entity', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_entity_source_config_id'), 'entity', ['source_config_id'], unique=False)
    op.create_index('ix_entity_source_config_value_type', 'entity', ['source_config_id', 'value_type'], unique=False)
    op.create_index('ix_entity_type_value_type', 'entity', ['type', 'value_type'], unique=False)
    op.create_index(op.f('ix_entity_value_type'), 'entity', ['value_type'], unique=False)
    op.create_index('uk_source_config_type_name', 'entity', ['source_config_id', 'type', 'normalized_name'], unique=True)
    op.create_table('event_entity',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('event_id', sa.CHAR(length=36), nullable=False),
    sa.Column('entity_id', sa.CHAR(length=36), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_event_entity_entity_id_entity'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['source_event.id'], name=op.f('fk_event_entity_event_id_source_event'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_entity'))
    )
    op.create_index('idx_entity_id', 'event_entity', ['entity_id'], unique=False)
    op.create_index('idx_event_id', 'event_entity', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_entity_entity_id'), 'event_entity', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_entity_event_id'), 'event_entity', ['event_id'], unique=False)
    op.create_index('uk_event_entity', 'event_entity', ['event_id', 'entity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_event_entity', table_name='event_entity')
    op.drop_index(op.f('ix_event_entity_event_id'), table_name='event_entity')
    op.drop_index(op.f('ix_event_entity_entity_id'), table_name='event_entity')
    op.drop_index('idx_event_id', table_name='event_entity')
    op.drop_index('idx_entity_id', table_name='event_entity')
    op.drop_table('event_entity')
    op.drop_index('uk_source_config_type_name', table_name='entity')
    op.drop_index(op.f('ix_entity_value_type'), table_name='entity')
    op.drop_index('ix_entity_type_value_type', table_name='entity')
    op.drop_index('ix_entity_source_config_value_type', table_name='entity')
    op.drop_index(op.f('ix_entity_source_config_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_normalized_name'), table_name='entity')
    op.drop_index(op.f('ix_entity_int_value'), table_name='entity')
    op.drop_index(op.f('ix_entity_float_value'), table_name='entity')
    op.drop_index(op.f('ix_entity_enum_value'), table_name='entity')
    op.drop_index(op.f('ix_entity_entity_type_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_datetime_value'), table_name='entity')
    op.drop_index('idx_source_config_type', table_name='entity')
    op.drop_index('idx_source_config_id', table_name='entity')
    op.drop_index('idx_normalized_name', table_name='entity')
    op.drop_index('idx_entity_type_id', table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_task_task_type'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_source_config_id'), table_name='task')
    op.drop_index(op.f('ix_task_article_id'), table_name='task')
    op.drop_index('idx_task_type', table_name='task')
    op.drop_index('idx_status_created', table_name='task')
    op.drop_index('idx_status', table_name='task')
    op.drop_index('idx_source_config_id', table_name='task')
    op.drop_index('idx_created_time', table_name='task')
    op.drop_index('idx_article_id', table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_source_event_source_type'), table_name='source_event')
    op.drop_index(op.f('ix_source_event_source_id'), table_name='source_event')
    op.drop_index(op.f('ix_source_event_source_config_id'), table_name='source_event')
    op.drop_index(op.f('ix_source_event_parent_id'), table_name='source_event')
    op.drop_index(op.f('ix_source_event_conversation_id'), table_name='source_event')
    op.drop_index(op.f('ix_source_event_chunk_id'), table_name='source_event')
    op.drop_index(op.f('ix_source_event_article_id'), table_name='source_event')
    op.drop_index('idx_start_time', table_name='source_event')
    op.drop_index('idx_source_rank', table_name='source_event')
    op.drop_index('idx_source_config_id', table_name='source_event')
    op.drop_index('idx_source', table_name='source_event')
    op.drop_index('idx_parent_level', table_name='source_event')
    op.drop_index('idx_parent_id', table_name='source_event')
    op.drop_index('idx_level', table_name='source_event')
    op.drop_index('idx_end_time', table_name='source_event')
    op.drop_index('idx_conversation_id', table_name='source_event')
    op.drop_index('idx_chunk_id', table_name='source_event')
    op.drop_index('idx_article_rank', table_name='source_event')
    op.drop_index('idx_article_id', table_name='source_event')
    op.drop_table('source_event')
    op.drop_index(op.f('ix_source_chunk_source_type'), table_name='source_chunk')
    op.drop_index(op.f('ix_source_chunk_source_id'), table_name='source_chunk')
    op.drop_index(op.f('ix_source_chunk_source_config_id'), table_name='source_chunk')
    op.drop_index(op.f('ix_source_chunk_conversation_id'), table_name='source_chunk')
    op.drop_index(op.f('ix_source_chunk_article_id'), table_name='source_chunk')
    op.drop_index('idx_source_config_id', table_name='source_chunk')
    op.drop_index('idx_source', table_name='source_chunk')
    op.drop_index('idx_created', table_name='source_chunk')
    op.drop_index('idx_conversation_id', table_name='source_chunk')
    op.drop_index('idx_article_id', table_name='source_chunk')
    op.drop_table('source_chunk')
    op.drop_index('uk_scope_source_config_article_type', table_name='entity_type')
    op.drop_index(op.f('ix_entity_type_source_config_id'), table_name='entity_type')
    op.drop_index(op.f('ix_entity_type_scope'), table_name='entity_type')
    op.drop_index(op.f('ix_entity_type_article_id'), table_name='entity_type')
    op.drop_index('idx_default_active', table_name='entity_type')
    op.drop_table('entity_type')
    op.drop_index(op.f('ix_chat_message_conversation_id'), table_name='chat_message')
    op.drop_index('idx_type', table_name='chat_message')
    op.drop_index('idx_sender_id', table_name='chat_message')
    op.drop_index('idx_del_flag', table_name='chat_message')
    op.drop_index('idx_conv_timestamp', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_article_section_article_id'), table_name='article_section')
    op.drop_index('idx_article_rank', table_name='article_section')
    op.drop_index('idx_article_id', table_name='article_section')
    op.drop_table('article_section')
    op.drop_index(op.f('ix_chat_conversation_source_config_id'), table_name='chat_conversation')
    op.drop_index('idx_source_last_msg', table_name='chat_conversation')
    op.drop_table('chat_conversation')
    op.drop_index(op.f('ix_article_source_config_id'), table_name='article')
    op.drop_index(op.f('ix_article_category'), table_name='article')
    op.drop_index('idx_source_config_status', table_name='article')
    op.drop_index('idx_source_config_id', table_name='article')
    op.drop_index('idx_category', table_name='article')
    op.drop_table('article')
    op.drop_table('source_config')
    op.drop_index(op.f('ix_model_config_type'), table_name='model_config')
    op.drop_index(op.f('ix_model_config_scenario'), table_name='model_config')
    op.drop_index(op.f('ix_model_config_is_active'), table_name='model_config')
    op.drop_index('idx_type_scenario_active_priority', table_name='model_config')
    op.drop_index('idx_type', table_name='model_config')
    op.drop_index('idx_scenario', table_name='model_config')
    op.drop_table('model_config')
    # ### end Alembic commands ###
